### ISSUE TITLE
Could I ask you about your paper for "Using Deep Learning to Predict Obstacle Trajectories for Collision Avoidance in Autonomous Vehicles"?

### ISSUE THREAD

**Issue by poweihuang17** [CogRob/path_prediction#1]
Hi,
My name is Po-wei Huang. I’m a master student at National Taiwan University.
Recently, I’ve read your paper about trajectory prediction by LSTM and encoder-decoder, and found that it’s related to my master thesis. 
(I’m conducting a research about vehicle trajectory prediction. So I need to compare my method with all of the baselines....)

Thus , my professor and I are thinking about reimplementing this for comparison.

Could I ask you about whether this is the code for the paper?

Thank you,
Po-wei Huang @ NTU

**Comment by poweihuang17** [comment]
@jaskaran1 Big thank you for your work.

**Comment by jaskaran1** [comment]
Hi Po-wei,
Can you give me your email?

**Comment by poweihuang17** [comment]
@jaskaran1  Big thank you for replying so swiftly!. My email is poweihuang17@gmail.com.

**Comment by poweihuang17** [comment]
Thank you. We're reimplementing it because we are comparing it on different dataset like NGSIM and our car, otherwise we could just reference your experiment result about KITTI on the paper. Thank you!
